# Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: spacedb
            - name: MYSQL_ROOT_PASSWORD
              value: milkyway

---
# Service definition
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 8000
      targetPort: 80
  type: LoadBalancer
