apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          imagePullPolicy: IfNotPresent
          command: ["/bin/prometheus"]
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
      restartPolicy: Always
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: "eureka-server"
        metrics_path: /actuator/prometheus
        scrape_interval: 5s
        static_configs:
          - targets: ["eureka-server:8036"]

      - job_name: "api-gateway"
        metrics_path: /actuator/prometheus
        scrape_interval: 5s
        static_configs:
          - targets: ["api-gateway:8080"]

      - job_name: "administration-service"
        metrics_path: /actuator/prometheus
        scrape_interval: 5s
        static_configs:
          - targets: ["administration-service:8090"]

      - job_name: "user-service"
        metrics_path: /actuator/prometheus
        scrape_interval: 5s
        static_configs:
          - targets: ["user-service:8100"]

      - job_name: "post-service"
        metrics_path: /actuator/prometheus
        scrape_interval: 5s
        static_configs:
          - targets: ["post-service:8110"]

      - job_name: "chat-service"
        metrics_path: /actuator/prometheus
        scrape_interval: 5s
        static_configs:
          - targets: ["chat-service:8120"]
